name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install Dependencies with pnpm
        run: |
          # Enable Corepack and prepare pnpm in the same shell
          corepack enable
          corepack prepare pnpm@latest --activate
          # Verify pnpm is available
          pnpm --version
          # Run your install:deps script which uses pnpm
          npm run install:deps

      - name: Build Host Application
        working-directory: ./host
        run: npm run build

      - name: Build Remote Application
        working-directory: ./remote
        run: npm run build

      - name: Prepare Deployment Directory
        run: |
          mkdir build-output
          # Copy host build output to the deployment root
          cp -R host/dist/* build-output/
          # Copy remote build output into a 'remote' subdirectory
          mkdir -p build-output/remote
          cp -R remote/dist/* build-output/remote/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build-output
