name: Build, Test, and Deploy Microfrontend Applications

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - app: host
            directory: './host'
          - app: remote
            directory: './remote'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: |
          cd ${{ matrix.directory }}
          pnpm install

      - name: Build Application
        run: |
          cd ${{ matrix.directory }}
          pnpm run build
        timeout-minutes: 10

      - name: Run Tests and Collect Coverage
        if: matrix.app == 'host' # Assuming only the host has tests to run
        run: |
          cd ${{ matrix.directory }}
          pnpm run test:coverage

      - name: Upload Coverage to Coveralls
        if: matrix.app == 'host' # Assuming coverage is only relevant for the host
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: '${{ matrix.directory }}/coverage/lcov.info' # Adjust path as needed

      - name: Deploy to Vercel
        if: matrix.app == 'host' # Assuming only the host is deployed to Vercel
        run: |
          cd ${{ matrix.directory }}
          npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
