name: Deploy to Vercel and Upload Coverage to Coveralls

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Clear pnpm store
        run: pnpm store prune || true # Avoids failure if pnpm is not yet installed

      - name: Enable Corepack
        run: corepack enable

      - name: Prepare pnpm
        run: corepack prepare pnpm@latest --activate

      - name: Check pnpm version
        run: pnpm -v

      - name: Install dependencies
        run: npm install:deps

      - name: Build Project
        run: VITE_LOG_LEVEL=debug pnpm build
        timeout-minutes: 10

      - name: Run Tests with Coverage
        run: pnpm test:coverage

      - name: Upload Coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }}
